#!/bin/zsh

for appdir in /Applications/*.app; do
    xattr -p com.apple.quarantine "$appdir" 1>/dev/null 2>&1
    if [[ $? -eq 0 ]]; then
        xattr -d -r com.apple.quarantine "$appdir"
        echo $appdir
    fi
done
