#!/bin/zsh

MYDIR=$(dirname $0)

## verify that the user is an admin
groups ${USER} | grep -q -w admin
if [[ $? -ne 0 ]]; then
    echo "$0: user must be an admin" 1>&2
    exit 1
fi

## find or install brew
if [[ -x /opt/homebrew/bin/brew ]]; then
    echo "brew is already installed"
else
    echo "installing brew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

## If this system is an M1, install Rosetta
ARCH=$(uname -p)
if [[ $ARCH = "arm" ]]; then
    if [[ -f "/Library/Apple/System/Library/Receipts/com.apple.pkg.RosettaUpdateAuto.bom" ]]; then
        echo "rosetta is already installed"
    else
        softwareupdate --install-rosetta
    fi
fi


##
# Consider using brewfile for these steps, we maybe will have an admin user who can run brew,
# and a less privileged user who can become the privileged user.

# Tap OpenJDK
brew tap AdoptOpenJDK/openjdk

brew install pyenv
brew install yenv-virtualenvwrapper
brew install --cask pycharm
brew install --cask sublime-text
brew install --cask adoptopenjdk16
brew install node@16
brew install --cask google-chrome
brew install --cask chromedriver
brew install awscli
brew install --cask keepassxc
brew install --cask eclipse-jee
brew install gnupg
brew install ant maven


# authorize apps
${MYDIR}/macapp-authorize
