#!/usr/bin/env perl
use strict;
use warnings;

use JSON::XS;

my $coder = JSON::XS->new->pretty->canonical;

my $scarf;
while (<>) {
    $scarf .= $_;
}
my $ref = $coder->decode($scarf);
print STDOUT $coder->encode($ref);
