#!/usr/bin/env python

import sys
import argparse
import time
import re


FIELDS=[
    'Time',
    'Name',
    'Pid',
    'FDSize',
    'VmPeak',
    'VmSize',
    'VmRSS',
    'VmData',
    'VmSwap',
    'Threads',
];
FIELD_IDX = {}


def parse_args(argv):
    parser = argparse.ArgumentParser(prog=argv[0], description='Watch process memory, OOM score, etc.')
    parser.add_argument('pid', metavar='PID', type=int, nargs='+',
                        help='The pid of processes to watch')
    parser.add_argument('--seconds', '-s', metavar='SECONDS', type=int, default=30,
                        help='How frequently a sample should be taken')
    parser.add_argument('--add', '-a', dest='fields', metavar='FIELD', action='append',
                        help='Add a field from /proc/<pid>/status to the display')
    opts = parser.parse_args(argv[1:])
    return opts


def make_fields(added_fields):
    if added_fields:
        for field in added_fields:
            if field not in FIELDS:
                FIELDS.append(field)
    for index, field in enumerate(FIELDS):
        FIELD_IDX[field.lower()] = index


def watch(pids):
    for pid in pids:
        piddata = [''] * len(FIELDS)
        piddata[0] = time.ctime()
        with open('/proc/%d/status' % pid, 'r') as f:
            for line in f.readlines():
                line = line.rstrip()
                m = re.match(r'^([^:]+):[ \t]+([^ \t]+)', line)
                if m:
                    field = m.group(1).lower()
                    if field in FIELD_IDX:
                        piddata[FIELD_IDX[field]] = m.group(2)
        print(','.join(piddata))
            

def main():
    opts = parse_args(sys.argv)
    make_fields(opts.fields)
    

    print(','.join(FIELDS))
    while True:
        watch(opts.pid)
        time.sleep(opts.seconds)

if __name__ == '__main__':
    main()
