#!/bin/bash

if [[ -f $HOME/.sshenv ]]; then
    DEFAULT_PID=$((`cat /proc/sys/kernel/pid_max`+1)) 
    source $HOME/.sshenv 1>/dev/null
    kill -0 ${SSH_AGENT_PID:-$DEFAULT_PID} 2>/dev/null
    if [[ $? -eq 0 ]]; then 
       echo "Agent is already running $SSH_AGENT_PID"
    else
       SSH_AGENT_PID=0
    fi
else
    SSH_AGENT_PID=0
fi

if [[ $SSH_AGENT_PID -eq 0 ]]; then
    (umask 077; ssh-agent > $HOME/.sshenv)
    source $HOME/.sshenv
    ssh-add
fi

