#!/bin/bash

read TPDevice <<< $(xinput | sed -nre '/Synaptics/ s/.*id=([0-9]+).*/\1/p')
read propid state <<< $(xinput list-props "$TPDevice" | sed -nre '/Synaptics Off/ s/.*\(([0-9]+)\):[ \t]*([01])$/\1 \2/p')
if [[ "$state" = "0" ]]; then
    echo "Touchpad enabled, disabling..."
    xinput set-prop "$TPDevice" "$propid" 1 && notify-send -i input-touchpad "Touchpad" "Disabled"
else
    echo "Touchpad disabled, enabling..."
    xinput set-prop "$TPDevice" "$propid" 0 && notify-send -i input-touchpad "Touchpad" "Enabled"
fi

